version: '3.8'

services:
    laravel:
      container_name: ficker_laravel
      image: gbzzz/laravel-php8.1
      ports:
        - 8080:80
      networks:
        - ficker
      volumes:
        #- /home/phpdro/Documents/projects/ficker-api:/app
      environment:
        - APP_ENV=local
      depends_on:
        - mysql

    mysql:
      container_name: ficker_mysql
      image: mysql:latest
      ports:
        - 3306:3306
      volumes:
        - './mysql:/var/lib/mysql'
      networks:
        - ficker
      environment:
        ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_ROOT_PASSWORD: ficker
        MYSQL_DATABASE: ficker
        MYSQL_USER: ficker
        MYSQL_PASSWORD: ficker

    phpmyadmin:
      container_name: ficker_phpmyadmin
      image: phpmyadmin:latest
      environment:
        - MYSQL_ROOT_PASSWORD=ficker
        - PMA_HOST=mysql
        - TZ=America/Maceio
      ports:
        - '9090:80'
      depends_on:
        - mysql
      networks:
        - ficker

networks:
  ficker: