services:
    laravel:
      container_name: ficker_back
      image: ghcr.io/phpdro/ficker-api/ficker-back:latest
      ports:
        - 8080:80
      networks:
        - ficker
      volumes:
        - /home/phpdro/Documents/projects/ficker-api:/app
      environment:
        - APP_ENV=local

    # front:
    #   container_name: ficker_front
    #   build:
    #     context: /home/phpdro/Documents/projects/ficker-front
    #     dockerfile: /home/phpdro/Documents/projects/ficker-front/Dockerfile
    #   ports:
    #     - 80:3000
    #   networks:
    #     - ficker

    mysql:
      container_name: ficker_db
      image: mysql:latest
      ports:
        - 3306:3306
      volumes:
        - './mysql:/var/lib/mysql'
      networks:
        - ficker
      environment:
        ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_ROOT_PASSWORD: ficker
        MYSQL_DATABASE: ficker
        MYSQL_USER: ficker
        MYSQL_PASSWORD: ficker

    phpmyadmin:
      container_name: ficker_phpmyadmin
      image: phpmyadmin:latest
      environment:
        - MYSQL_ROOT_PASSWORD=ficker
        - PMA_HOST=mysql
        - TZ=America/Maceio
      ports:
        - '9090:80'
      depends_on:
        - mysql
      networks:
        - ficker

networks:
  ficker: