name: Pedrops e Alambda

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Image build
          run: docker build -t ficker-back .  

        - name: Enviar para ghcr.io
          run: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker tag ficker-back phpdro/ficker-back:latest
            docker push phpdro/ficker-back:latest